govApi.url.confiscations=https://data.gov.gr/api/v1/query/ktm_confs
govApi.url.areas=https://data.gov.gr/datasets/ktm_harea
govApi.url.cadastralRecords=https://data.gov.gr/datasets/cadastre_plot
govApi.url.mortgages=https://data.gov.gr/datasets/ktm_liens
govApi.url.owners=https://data.gov.gr/datasets/ktm_owners
govApi.url.properties=https://data.gov.gr/datasets/ktm_hplots
govApi.url.propertyDealings=https://data.gov.gr/datasets/ktm_transactions
govApi.key=bcd70e6ff2b918204fd3ea4602f4fb3a1ecbeb28

# DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ota_2
spring.datasource.username=springuser
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=ota_observatory
spring.jpa.show-sql=true
