govApi.url.confiscations=https://data.gov.gr/api/v1/query/ktm_confs
govApi.url.areas=https://data.gov.gr/api/v1/query/ktm_confs
govApi.url.cadastralRecords=https://data.gov.gr/datasets/cadastre_plot
govApi.url.mortgages=https://data.gov.gr/datasets/ktm_liens
govApi.url.owners=https://data.gov.gr/datasets/ktm_owners
govApi.url.properties=https://data.gov.gr/datasets/ktm_hplots
govApi.url.propertyDealings=https://data.gov.gr/datasets/ktm_transactions
govApi.key=

# DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ota_2
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=ota_observatory

server.port=8080

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot
